doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            blog_post_id:  App\BlogPosts\Infrastructure\Database\Type\DoctrineBlogPostIdType
            async_message_id:  App\Shared\Infrastructure\Database\Type\AsyncMessage\AsyncMessageIdType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            BlogPosts:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/BlogPosts/Infrastructure/Database/ORM'
                prefix: 'App\BlogPosts\Domain\Aggregate\BlogPost'
                alias: BlogPosts
            AsyncMessage:
                type: xml
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Database/ORM'
                prefix: 'App\Shared\Domain\Aggregate\AsyncMessage'
                alias: AsyncMessages