version: "3.9"

services:
  php-fpm:
    container_name: training_php_fpm
    build:
      context: ./../
      dockerfile: docker/php-fpm/Dockerfile
      args:
        - ENABLE_XDEBUG=${ENABLE_XDEBUG}
    ports:
      - ${PHP_FPM_PORT}:9000
    volumes:
      - ./../:/var/www
    environment:
      PHP_IDE_CONFIG: "serverName=training"
  nginx:
    container_name: training_nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HTTP_PORT}:80
    volumes:
      - ./../:/var/www
    depends_on:
      - php-fpm
  postgres:
    container_name: training_postgres
    build:
      context: ./postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data:rw
  mongodb:
    container_name: training_mongodb
    image: mongo:latest
    ports:
      - ${MONGODB_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
  rabbitmq:
    container_name: training_rabbitmq
    image: rabbitmq:management
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
volumes:
  db_data:
  mongo_data:
  rabbitmq_data:
  rabbitmq_logs: