kernel:
    resource: ../src/Shared/Infrastructure/Kernel.php
    type: attribute

controllers:
    resource: ../src/Shared/Infrastructure/Controller/
    type: attribute

blog_posts:
    resource: ../src/BlogPosts/Presentation/Controller/REST/
    type: attribute